package com.louisgautier.designsystem.theme.color

// Day Theme (Light Mode)
fun provideDayColors(): AppColors = AppColors(
    bg = TokenClass.white,
    bgSubtle = TokenClass.gray50,
    bgMuted = TokenClass.gray100,
    bgEmphasized = TokenClass.gray200,
    bgInverted = TokenClass.black,
    bgPanel = TokenClass.white,
    bgError = TokenClass.red50,
    bgWarning = TokenClass.orange50,
    bgSuccess = TokenClass.green50,
    bgInfo = TokenClass.blue50,

    border = TokenClass.gray200,
    borderMuted = TokenClass.gray100,
    borderSubtle = TokenClass.gray50,
    borderEmphasized = TokenClass.gray300,
    borderInverted = TokenClass.gray800,
    borderError = TokenClass.red500,
    borderWarning = TokenClass.orange500,
    borderSuccess = TokenClass.green200,
    borderInfo = TokenClass.blue500,

    // Foreground / Text
    fg = TokenClass.black,
    fgMuted = TokenClass.gray600,
    fgSubtle = TokenClass.gray400,
    fgInverted = TokenClass.gray50,
    fgError = TokenClass.red500,
    fgWarning = TokenClass.orange600,
    fgSuccess = TokenClass.green600,
    fgInfo = TokenClass.blue600,

    grayFamily = ColorFamily(
        contrast = TokenClass.white,
        fg = TokenClass.gray800,
        subtle = TokenClass.gray100,
        muted = TokenClass.gray200,
        emphasized = TokenClass.gray300,
        solid = TokenClass.gray900,
        focusRing = TokenClass.gray400,
    ),
    redFamily = ColorFamily(
        contrast = TokenClass.white,
        fg = TokenClass.red700,
        subtle = TokenClass.red100,
        muted = TokenClass.red200,
        emphasized = TokenClass.red300,
        solid = TokenClass.red600,
        focusRing = TokenClass.red500,
    ),
    pinkFamily = ColorFamily(
        contrast = TokenClass.white,
        fg = TokenClass.pink700,
        subtle = TokenClass.pink100,
        muted = TokenClass.pink200,
        emphasized = TokenClass.pink300,
        solid = TokenClass.pink600,
        focusRing = TokenClass.pink500,
    ),
    purpleFamily = ColorFamily(
        contrast = TokenClass.white,
        fg = TokenClass.purple700,
        subtle = TokenClass.purple100,
        muted = TokenClass.purple200,
        emphasized = TokenClass.purple300,
        solid = TokenClass.purple600,
        focusRing = TokenClass.purple500,
    ),
    cyanFamily = ColorFamily(
        contrast = TokenClass.white,
        fg = TokenClass.cyan700,
        subtle = TokenClass.cyan100,
        muted = TokenClass.cyan200,
        emphasized = TokenClass.cyan300,
        solid = TokenClass.cyan600,
        focusRing = TokenClass.cyan500,
    ),
    blueFamily = ColorFamily(
        contrast = TokenClass.white,
        fg = TokenClass.blue700,
        subtle = TokenClass.blue100,
        muted = TokenClass.blue200,
        emphasized = TokenClass.blue300,
        solid = TokenClass.blue600,
        focusRing = TokenClass.blue500,
    ),
    tealFamily = ColorFamily(
        contrast = TokenClass.white,
        fg = TokenClass.teal700,
        subtle = TokenClass.teal100,
        muted = TokenClass.teal200,
        emphasized = TokenClass.teal300,
        solid = TokenClass.teal600,
        focusRing = TokenClass.teal500,
    ),
    greenFamily = ColorFamily(
        contrast = TokenClass.white,
        fg = TokenClass.green700,
        subtle = TokenClass.green100,
        muted = TokenClass.green200,
        emphasized = TokenClass.green300,
        solid = TokenClass.green600,
        focusRing = TokenClass.green500,
    ),
    yellowFamily = ColorFamily(
        contrast = TokenClass.black,
        fg = TokenClass.yellow800,
        subtle = TokenClass.yellow100,
        muted = TokenClass.yellow200,
        emphasized = TokenClass.yellow300,
        solid = TokenClass.yellow300,
        focusRing = TokenClass.yellow500,
    ),
    orangeFamily = ColorFamily(
        contrast = TokenClass.white,
        fg = TokenClass.orange700,
        subtle = TokenClass.orange100,
        muted = TokenClass.orange200,
        emphasized = TokenClass.orange300,
        solid = TokenClass.orange600,
        focusRing = TokenClass.orange500,
    ),
)

