package com.louisgautier.designsystem.theme.color

// Night Theme (Dark Mode)
fun provideNightColors(): AppColors = AppColors(
    bg = TokenClass.black,
    bgSubtle = TokenClass.gray950,
    bgMuted = TokenClass.gray900,
    bgEmphasized = TokenClass.gray800,
    bgInverted = TokenClass.white,
    bgPanel = TokenClass.gray950,
    bgError = TokenClass.red950,
    bgWarning = TokenClass.orange950,
    bgSuccess = TokenClass.green950,
    bgInfo = TokenClass.blue950,

    border = TokenClass.gray800,
    borderMuted = TokenClass.gray900,
    borderSubtle = TokenClass.gray950,
    borderEmphasized = TokenClass.gray600,
    borderInverted = TokenClass.gray700,
    borderError = TokenClass.red200,
    borderWarning = TokenClass.orange400,
    borderSuccess = TokenClass.green400,
    borderInfo = TokenClass.blue400,

    // Foreground / Text
    fg = TokenClass.gray50,
    fgMuted = TokenClass.gray400,
    fgSubtle = TokenClass.gray500,
    fgInverted = TokenClass.black,
    fgError = TokenClass.red400,
    fgWarning = TokenClass.orange300,
    fgSuccess = TokenClass.green300,
    fgInfo = TokenClass.blue300,

    grayFamily = ColorFamily(
        contrast = TokenClass.black,
        fg = TokenClass.gray200,
        subtle = TokenClass.gray900,
        muted = TokenClass.gray800,
        emphasized = TokenClass.gray700,
        solid = TokenClass.white,
        focusRing = TokenClass.gray400,
    ),
    redFamily = ColorFamily(
        TokenClass.white,
        TokenClass.red300,
        TokenClass.red900,
        TokenClass.red800,
        TokenClass.red700,
        TokenClass.red600,
        TokenClass.red500,
    ),
    pinkFamily = ColorFamily(
        contrast = TokenClass.white,
        fg = TokenClass.pink300,
        subtle = TokenClass.pink900,
        muted = TokenClass.pink800,
        emphasized = TokenClass.pink700,
        solid = TokenClass.pink600,
        focusRing = TokenClass.pink500,
    ),
    purpleFamily = ColorFamily(
        contrast = TokenClass.white,
        fg = TokenClass.purple300,
        subtle = TokenClass.purple900,
        muted = TokenClass.purple800,
        emphasized = TokenClass.purple700,
        solid = TokenClass.purple600,
        focusRing = TokenClass.purple500,
    ),
    cyanFamily = ColorFamily(
        contrast = TokenClass.white,
        fg = TokenClass.cyan300,
        subtle = TokenClass.cyan900,
        muted = TokenClass.cyan800,
        emphasized = TokenClass.cyan700,
        solid = TokenClass.cyan600,
        focusRing = TokenClass.cyan500,
    ),
    blueFamily = ColorFamily(
        contrast = TokenClass.white,
        fg = TokenClass.blue300,
        subtle = TokenClass.blue900,
        muted = TokenClass.blue800,
        emphasized = TokenClass.blue700,
        solid = TokenClass.blue600,
        focusRing = TokenClass.blue500,
    ),
    tealFamily = ColorFamily(
        contrast = TokenClass.white,
        fg = TokenClass.teal300,
        subtle = TokenClass.teal900,
        muted = TokenClass.teal800,
        emphasized = TokenClass.teal700,
        solid = TokenClass.teal600,
        focusRing = TokenClass.teal500,
    ),
    greenFamily = ColorFamily(
        contrast = TokenClass.white,
        fg = TokenClass.green300,
        subtle = TokenClass.green900,
        muted = TokenClass.green800,
        emphasized = TokenClass.green700,
        solid = TokenClass.green600,
        focusRing = TokenClass.green500,
    ),
    yellowFamily = ColorFamily(
        contrast = TokenClass.black,
        fg = TokenClass.yellow300,
        subtle = TokenClass.yellow900,
        muted = TokenClass.yellow800,
        emphasized = TokenClass.yellow700,
        solid = TokenClass.yellow300,
        focusRing = TokenClass.yellow500,
    ),
    orangeFamily = ColorFamily(
        contrast = TokenClass.black,
        fg = TokenClass.orange300,
        subtle = TokenClass.orange900,
        muted = TokenClass.orange800,
        emphasized = TokenClass.orange700,
        solid = TokenClass.orange600,
        focusRing = TokenClass.orange500,
    )
)
